# Generated by Django 6.0.2 on 2026-03-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('batch', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('experience', models.CharField(blank=True, default='', max_length=50)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('available', models.BooleanField(default=True)),
                ('linkedin', models.URLField(blank=True, default='')),
                ('avatar', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Alumni',
                'ordering': ['-created_at'],
            },
        ),
    ]
